create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  usuario text not null unique,
  password_hash text not null,
  rol text not null default 'USUARIO',
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usuarios_rol_check
    check (rol in ('ADMIN', 'USUARIO'))
);

create or replace function public.set_usuarios_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row
execute function public.set_usuarios_updated_at();

alter table public.usuarios disable row level security;

insert into public.usuarios (usuario, password_hash, rol, activo)
values (
  'admin',
  crypt('admin123', gen_salt('bf', 10)),
  'ADMIN',
  true
)
on conflict (usuario) do nothing;
