create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_empresa_codigo()
returns trigger
language plpgsql
as $$
begin
  new.codigo = lower(trim(new.codigo));
  return new;
end;
$$;

create or replace function public.normalize_usuario_login()
returns trigger
language plpgsql
as $$
begin
  new.usuario = lower(trim(new.usuario));
  return new;
end;
$$;

create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  nombre_comercial text,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint empresas_codigo_check check (char_length(trim(codigo)) >= 3),
  constraint empresas_nombre_check check (char_length(trim(nombre)) >= 2)
);

drop trigger if exists trg_empresas_updated_at on public.empresas;
create trigger trg_empresas_updated_at
before update on public.empresas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_empresas_normalize_codigo on public.empresas;
create trigger trg_empresas_normalize_codigo
before insert or update on public.empresas
for each row
execute function public.normalize_empresa_codigo();

create table if not exists public.config_suscripcion (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null unique references public.empresas(id) on delete cascade,
  plan varchar(50) not null default 'BASICO',
  limite_usuarios integer not null default 5,
  activa boolean not null default true,
  fecha_inicio timestamptz not null default now(),
  fecha_expiracion timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint config_suscripcion_limite_check check (limite_usuarios >= 1)
);

drop trigger if exists trg_config_suscripcion_updated_at on public.config_suscripcion;
create trigger trg_config_suscripcion_updated_at
before update on public.config_suscripcion
for each row
execute function public.set_updated_at();

create table if not exists public.config_empresa (
  empresa_id bigint primary key references public.empresas(id) on delete cascade,
  nombre_app text not null default 'Qr asistencia',
  logo_url text,
  color_primario text,
  drive_folder_id text,
  drive_folder_name text,
  sheets_spreadsheet_id text,
  sheets_spreadsheet_name text,
  sheets_spreadsheet_url text,
  google_sync_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_config_empresa_updated_at on public.config_empresa;
create trigger trg_config_empresa_updated_at
before update on public.config_empresa
for each row
execute function public.set_updated_at();

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  usuario text not null,
  password_hash text not null,
  nombre text,
  rol text not null default 'USUARIO',
  activo boolean not null default true,
  ultimo_acceso_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usuarios_rol_check check (rol in ('ADMIN', 'SUPERVISOR', 'USUARIO')),
  constraint usuarios_empresa_usuario_unique unique (empresa_id, usuario)
);

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row
execute function public.set_updated_at();

drop trigger if exists trg_usuarios_normalize_usuario on public.usuarios;
create trigger trg_usuarios_normalize_usuario
before insert or update on public.usuarios
for each row
execute function public.normalize_usuario_login();

create table if not exists public.proyecto (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  "No." text not null,
  "NameProyect" text not null,
  "Client" text,
  "OC" text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint proyecto_empresa_numero_unique unique (empresa_id, "No.")
);

drop trigger if exists trg_proyecto_updated_at on public.proyecto;
create trigger trg_proyecto_updated_at
before update on public.proyecto
for each row
execute function public.set_updated_at();

create table if not exists public.registros (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  proyecto_id bigint references public.proyecto(id) on delete set null,
  usuario_id bigint references public.usuarios(id) on delete set null,
  "DPI" text not null,
  nombre text not null,
  proyecto text not null,
  tipo text not null,
  fecha_hora timestamptz not null default now(),
  usuario_logueado text not null,
  observaciones text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_usuarios_empresa_activo
  on public.usuarios (empresa_id, activo);

create index if not exists idx_proyecto_empresa_activo
  on public.proyecto (empresa_id, activo);

create index if not exists idx_registros_empresa_fecha
  on public.registros (empresa_id, fecha_hora desc);

create index if not exists idx_registros_usuario_fecha
  on public.registros (usuario_logueado, fecha_hora desc);

comment on table public.empresas is
  'Empresas o clientes que usan la app general.';

comment on table public.config_suscripcion is
  'Configuracion comercial por empresa: plan, limite de usuarios y vigencia.';

comment on table public.config_empresa is
  'Configuracion visual e integraciones futuras por empresa.';

comment on table public.usuarios is
  'Usuarios operativos por empresa. Mantiene compatibilidad parcial con la app actual.';

comment on table public.proyecto is
  'Proyectos por empresa. Se conserva el nombre de tabla actual para facilitar la migracion del frontend.';

comment on table public.registros is
  'Historial de asistencias y movimientos por empresa.';

alter table public.empresas disable row level security;
alter table public.config_suscripcion disable row level security;
alter table public.config_empresa disable row level security;
alter table public.usuarios disable row level security;
alter table public.proyecto disable row level security;
alter table public.registros disable row level security;
