import postgres from 'npm:postgres@3.4.5';

let ensureConfigSchemaPromise: Promise<void> | null = null;

/**
 * Algunos proyectos remotos todavía no tienen sincronizada la tabla
 * configuracion_global con las columnas nuevas de Drive/Sheets.
 *
 * Esta rutina hace la corrección mínima en caliente usando la conexión SQL
 * remota del proyecto para que las Edge Functions no fallen por columnas
 * ausentes.
 */
export async function ensureConfigSchema(): Promise<void> {
  const dbUrl = Deno.env.get('SUPABASE_DB_URL');
  if (!dbUrl) return;

  if (ensureConfigSchemaPromise != null) {
    return ensureConfigSchemaPromise;
  }

  ensureConfigSchemaPromise = (async () => {
    const sql = postgres(dbUrl, {
      prepare: false,
      max: 1,
      idle_timeout: 5,
      connect_timeout: 10,
      ssl: 'require',
    });

    try {
      await sql.unsafe(`
        CREATE TABLE IF NOT EXISTS public.configuracion_global (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          sheets_spreadsheet_id TEXT,
          sheets_spreadsheet_name TEXT,
          sheets_spreadsheet_url TEXT,
          sheets_auto_sync BOOLEAN DEFAULT FALSE,
          drive_folder_id TEXT,
          drive_folder_name TEXT,
          drive_admin_google_email TEXT,
          drive_admin_refresh_token_enc TEXT,
          drive_admin_linked_at TIMESTAMPTZ
        );
      `);

      await sql.unsafe(`
        ALTER TABLE public.configuracion_global
          ADD COLUMN IF NOT EXISTS sheets_spreadsheet_id TEXT,
          ADD COLUMN IF NOT EXISTS sheets_spreadsheet_name TEXT,
          ADD COLUMN IF NOT EXISTS sheets_spreadsheet_url TEXT,
          ADD COLUMN IF NOT EXISTS sheets_auto_sync BOOLEAN DEFAULT FALSE,
          ADD COLUMN IF NOT EXISTS drive_folder_id TEXT,
          ADD COLUMN IF NOT EXISTS drive_folder_name TEXT,
          ADD COLUMN IF NOT EXISTS drive_admin_google_email TEXT,
          ADD COLUMN IF NOT EXISTS drive_admin_refresh_token_enc TEXT,
          ADD COLUMN IF NOT EXISTS drive_admin_linked_at TIMESTAMPTZ;
      `);
    } finally {
      await sql.end();
    }
  })().catch((error) => {
    ensureConfigSchemaPromise = null;
    throw error;
  });

  return ensureConfigSchemaPromise;
}
