-- ─────────────────────────────────────────────────────
-- Migration: app campaigns + campaign events
-- ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.app_campaigns (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type             TEXT        NOT NULL CHECK (type IN ('modal', 'banner', 'tooltip', 'badge')),
  title            TEXT        NOT NULL,
  body             TEXT        NOT NULL,
  cta_label        TEXT,
  cta_route        TEXT,
  target_roles     TEXT[]      NOT NULL DEFAULT '{}'::TEXT[],
  target_screen    TEXT,
  target_key       TEXT,
  badge_count      INTEGER,
  starts_at        TIMESTAMPTZ,
  ends_at          TIMESTAMPTZ,
  priority         INTEGER     NOT NULL DEFAULT 0,
  step_order       INTEGER     NOT NULL DEFAULT 0,
  min_app_version  TEXT,
  max_app_version  TEXT,
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_campaign_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT      NOT NULL REFERENCES public.app_campaigns(id) ON DELETE CASCADE,
  usuario_id  BIGINT      NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  action      TEXT        NOT NULL CHECK (action IN ('seen', 'dismissed', 'completed', 'clicked')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_campaigns_active_screen
  ON public.app_campaigns(target_screen, priority DESC, step_order ASC)
  WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_app_campaigns_active_window
  ON public.app_campaigns(starts_at, ends_at)
  WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_app_campaign_events_usuario_campaign
  ON public.app_campaign_events(usuario_id, campaign_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_app_campaigns_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_app_campaigns_updated_at ON public.app_campaigns;
CREATE TRIGGER trg_app_campaigns_updated_at
BEFORE UPDATE ON public.app_campaigns
FOR EACH ROW
EXECUTE FUNCTION public.set_app_campaigns_updated_at();

ALTER TABLE public.app_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_campaign_events ENABLE ROW LEVEL SECURITY;
